[application]
name = "dioxus-demo"
default_platform = "web"
out_dir = "dist"

[web.app]
title = "dioxus-demo"
base_path = "/"

[web.watcher]
index_on_404 = true
watch_path = ["src", "public"]

[web.resource]
style = []
# 配置静态资源目录
dir = "public"

[web.resource.dev]
include = []

[web.serve]
port = 8081
